In [124]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns; sns.set()
from sklearn.cluster import KMeans
import scipy.optimize as opt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler

dtrain = pd.read_csv('/Users/youqizheng/Documents/CISC151/Assignments/Assignment 3/Assignment 3 attached files Mar 19, 2020 1026 AM/digitDset_train.csv')
dtest = pd.read_csv('/Users/youqizheng/Documents/CISC151/Assignments/Assignment 3/Assignment 3 attached files Mar 19, 2020 1026 AM/digitDset_test.csv')



# KMeans models

In [129]:
dtrain1 = dtrain.iloc[:,0:64]
x = dtrain1.values[:,1:]
dset = StandardScaler().fit_transform(x)

cluster_n = 3
k_means = KMeans(init = "k-means++", n_clusters = cluster_n, n_init = 12)
k_means.fit(dset)
labels = k_means.labels_

k_means_centers = k_means.cluster_centers_
print(labels)
print(k_means_centers)

dtrain['cluster'] = labels
dtrain.head(5)

dtrain.groupby('cluster').mean()

[1 2 2 ... 1 1 2]
[[ 2.85850219e-01  5.12126365e-01  4.03907915e-01 -2.36016920e-03
  -1.14842210e-01 -2.32424400e-01 -1.32873992e-01  2.34107076e-02
   4.75275583e-01  4.91752074e-01 -6.49828026e-02  1.76550001e-01
   3.89029953e-02 -2.85842129e-01 -1.53740351e-01  3.67420107e-02
   2.91062310e-01  2.85221386e-02 -8.13774725e-02  4.00472000e-01
  -8.13313848e-02 -3.57341271e-01 -1.12958171e-01  3.20642671e-02
  -2.10319764e-01 -2.93745149e-01  2.94693549e-01  4.53870303e-01
  -2.23556626e-01 -4.36627463e-01 -4.85833941e-02 -3.61929449e-02
  -5.29141880e-01 -5.72379758e-01  1.94253501e-02  4.16601815e-02
  -3.17037093e-01 -3.25174007e-01  0.00000000e+00 -8.68853782e-02
  -3.77171638e-01 -3.65845931e-01 -1.48825473e-01 -2.04511620e-01
  -1.40811421e-01 -5.35356585e-02 -7.35638962e-02 -5.64362538e-02
   6.97696649e-02  1.99084317e-01 -6.44235077e-02 -1.46882797e-02
   2.34598676e-01  1.38016154e-01 -1.95612713e-02  1.60258386e-02
   2.25865028e-01  4.87866754e-01  4.12823142e-01  2.04761

0         1         6         15         12        1.1       0.1  \
cluster                                                                       
0        0.0  0.548958  7.853646  13.525521  11.440625   4.861979  0.604167   
1        0.0  0.010329  2.519249  10.309859  10.180282   2.264789  0.059155   
2        0.0  0.102748  3.810036   9.761051  13.093190  11.109916  4.875747   

              0.2       0.3         7  ...      0.21      0.22      0.23  \
cluster                                ...                                 
0        0.002604  0.004167  3.409375  ...  0.133333  0.000521  0.492708   
1        0.000000  0.000000  0.479812  ...  0.292019  0.000000  0.027230   
2        0.643967  0.000000  0.514934  ...  0.000000  0.000000  0.127838   

              6.3       14.1        7.4       1.3      0.24      0.25  \
cluster                                                                 
0        8.285417  13.731771  12.484375  7.892708  2.848958  0.348438   
1        2.543662  10.571831  13.646948  7.611268  2.106103  0.097653   
2        4.497013   9.581840   6.338112  2.813620  0.402628  0.000000   

             0.26  
cluster            
0        4.667187  
1        3.337089  
2        5.589008  

[3 rows x 65 columns]

In [130]:
dtrain1 = dtrain.iloc[:,0:64]
x = dtrain1.values[:,1:]
dset = StandardScaler().fit_transform(x)

cluster_n = 10
k_means = KMeans(init = "k-means++", n_clusters = cluster_n, n_init = 12)
k_means.fit(dset)
labels = k_means.labels_

k_means_centers = k_means.cluster_centers_
print(labels)
print(k_means_centers)

dtrain['cluster'] = labels
dtrain.head(5)

dtrain.groupby('cluster').mean()

[1 0 8 ... 7 7 0]
[[ 1.48601171e-01  4.20121862e-01  4.01088963e-01  5.46522000e-01
   1.06764140e+00  1.09039588e+00  6.55844913e-02 -2.36322601e-02
  -2.40274005e-01 -1.54335008e-01 -4.31101104e-01 -1.43609333e-01
   8.48964671e-01  1.17425165e+00  2.26871806e-02 -4.14763135e-02
  -4.55360313e-01 -1.11788978e+00 -9.11611298e-01 -1.66712545e-02
   7.83662260e-01  4.78305181e-01 -9.60312747e-02 -3.23677144e-02
  -4.42973116e-01 -7.63346818e-01 -2.35658259e-01  5.79709605e-01
   7.09635206e-01  3.38988149e-01 -4.85833941e-02 -3.61929449e-02
  -1.62949137e-01  1.15482604e-01  6.82177563e-01  8.08548637e-01
   4.10563614e-01  3.65834524e-01  0.00000000e+00 -8.68853782e-02
  -2.30168884e-01 -3.98986298e-01  7.49485991e-01  3.84460540e-01
  -8.86733346e-01 -6.50399518e-01 -9.30646045e-02 -6.61132103e-02
  -3.09229374e-01 -4.60548625e-01  6.96943569e-01 -9.20853908e-01
  -1.46625922e+00 -7.58550580e-01 -1.93227192e-01 -1.61775027e-02
   1.92685356e-01  5.72152311e-01 -1.19932748e-01 -1.93706

0         1          6         15         12        1.1        0.1  \
cluster                                                                         
0        0.0  0.429975   7.427518  13.513514  13.931204  11.498771   5.063882   
1        0.0  0.029412   4.593583  13.197861  10.935829   2.617647   0.058824   
2        0.0  1.106145  10.960894  13.918994   6.374302   0.673184   0.008380   
3        0.0  0.226978   5.726329  12.979248  12.587549   6.386511   0.915694   
4        0.0  0.000000   3.522388  11.194030  12.253731  11.701493  11.940299   
5        0.0  0.448555   7.687861  13.680925  12.628902   5.645087   0.862428   
6        0.0  0.000000   0.145390   5.705674  12.024823   2.556738   0.170213   
7        0.0  0.005236   2.227749  10.913613   7.869110   1.086387   0.005236   
8        0.0  0.013793   0.320690   4.255172  12.055172  11.362069   3.158621   
9        0.0  0.000000   0.000000   3.730769  14.692308   4.769231   0.000000   

              0.2       0.3         7  ...      0.21      0.22      0.23  \
cluster                                ...                                 
0        0.211302  0.000000  1.226044  ...  0.000000  0.000000  0.461916   
1        0.000000  0.000000  1.165775  ...  0.000000  0.000000  0.018717   
2        0.000000  0.000000  5.142458  ...  0.597765  0.000000  1.131285   
3        0.002594  0.010376  2.119326  ...  0.002594  0.000000  0.182879   
4        6.462687  0.000000  0.149254  ...  0.000000  0.000000  0.000000   
5        0.005780  0.000000  3.361850  ...  0.046243  0.000000  0.359538   
6        0.010638  0.000000  0.003546  ...  0.000000  0.000000  0.046099   
7        0.000000  0.000000  0.172775  ...  0.814136  0.000000  0.023560   
8        0.051724  0.000000  0.320690  ...  0.000000  0.000000  0.006897   
9        0.000000  0.000000  0.000000  ...  0.000000  0.038462  0.230769   

               6.3       14.1        7.4        1.3       0.24      0.25  \
cluster                                                                    
0         8.705160  11.422604   1.793612   0.257985   0.017199  0.000000   
1         4.601604  13.606952  13.344920   5.572193   0.195187  0.000000   
2        11.008380  14.125698  13.256983  12.603352  10.016760  1.815642   
3         6.230869  13.380026  11.369650   4.734112   0.575875  0.003891   
4         4.567164  11.895522   4.746269   0.253731   0.000000  0.000000   
5         8.189595  14.197688  13.369942   8.357225   1.597688  0.018497   
6         0.269504   6.563830  12.436170   2.765957   0.014184  0.000000   
7         2.209424  10.617801  14.541885  12.842932   5.646597  0.272251   
8         0.193103   4.882759  11.231034   7.713793   1.368966  0.000000   
9         0.230769   5.076923  14.384615   3.653846   0.000000  0.000000   

             0.26  
cluster            
0        6.697789  
1        0.040107  
2        2.047486  
3        4.779507  
4        6.388060  
5        5.642775  
6        4.017730  
7        5.986911  
8        4.148276  
9        3.923077  

[10 rows x 65 columns]

In [131]:
dtrain1 = dtrain.iloc[:,0:64]
x = dtrain1.values[:,1:]
dset = StandardScaler().fit_transform(x)

cluster_n = 30
k_means = KMeans(init = "k-means++", n_clusters = cluster_n, n_init = 12)
k_means.fit(dset)
labels = k_means.labels_

k_means_centers = k_means.cluster_centers_
print(labels)
print(k_means_centers)

dtrain['cluster'] = labels
dtrain.head(5)

dtrain.groupby('cluster').mean()

[10  4 20 ...  9  9 14]
[[-0.34738369 -0.91888009 -0.24201968 ...  1.3865939   2.1518631
   1.05771747]
 [ 0.10229324  0.4586429   0.2019436  ... -0.65423518 -0.51446529
  -0.17576425]
 [-0.29245421 -0.08264627  0.1644369  ...  0.4645178  -0.15459082
  -0.15984769]
 ...
 [-0.34738369 -1.18354205  0.04576223 ...  0.74423427 -0.5228807
  -0.17576425]
 [-0.34738369 -1.02744608 -0.64902844 ... -1.03648323 -0.5228807
  -0.17576425]
 [-0.34738369 -0.61084874  0.36544829 ... -0.20874773 -0.33977088
  -0.16960082]]


0         1          6         15         12        1.1        0.1  \
cluster                                                                         
0        0.0  0.000000   1.225806  10.774194  10.290323   0.677419   0.000000   
1        0.0  0.389831   7.605932  12.665254  13.940678  11.957627   3.775424   
2        0.0  0.047619   5.098901  12.505495  12.985348   6.487179   0.534799   
3        0.0  0.000000   0.013699   3.794521  12.335616   3.219178   0.020548   
4        0.0  0.439024   8.597561  14.439024  14.762195  10.018293   1.359756   
5        0.0  0.000000   0.426316   9.773684  11.078947   1.763158   0.000000   
6        0.0  0.048611   4.000000  11.951389  11.784722   4.527778   0.208333   
7        0.0  0.000000   1.703704   7.592593  12.111111   8.962963   5.629630   
8        0.0  0.119403   8.492537  13.910448   6.656716   0.701493   0.000000   
9        0.0  0.019608   4.660131  12.215686   3.339869   0.294118   0.000000   
10       0.0  0.038462   4.098901  13.543956  11.120879   2.153846   0.021978   
11       0.0  4.048193  14.807229  14.036145   7.084337   2.144578   0.337349   
12       0.0  0.000000   4.065217  12.173913  12.565217  12.413043  13.760870   
13       0.0  0.000000   0.000000   3.142857  14.761905   4.904762   0.000000   
14       0.0  0.126506   6.072289  13.078313  14.265060  14.343373   9.897590   
15       0.0  0.095541   6.471338  13.681529  11.859873   3.331210   0.114650   
16       0.0  0.005236   4.968586  12.921466  10.842932   3.047120   0.094241   
17       0.0  0.000000   0.750000  15.250000  13.250000   0.750000   0.000000   
18       0.0  0.678571   9.613095  13.428571  11.785714   7.672619   1.196429   
19       0.0  0.013605   0.027211   1.578231  11.571429  11.346939   1.108844   
20       0.0  0.000000   1.091549   7.542254  12.880282  12.154930   5.176056   
21       0.0  0.000000   0.000000   4.800000  14.400000   2.600000   0.000000   
22       0.0  0.597458  10.322034  13.915254   6.597458   0.627119   0.000000   
23       0.0  0.848485   9.084175  14.067340  13.202020   5.525253   0.417508   
24       0.0  2.000000   0.000000  13.000000  12.000000   3.000000   0.000000   
25       0.0  0.263158   7.287449  13.785425  12.182186   4.886640   0.676113   
26       0.0  0.000000   0.250000   9.375000  12.250000   2.125000   1.750000   
27       0.0  0.000000   0.000000  12.000000  16.000000  10.000000   0.000000   
28       0.0  0.000000   0.722973   9.040541  10.695946   1.310811   0.689189   
29       0.0  0.000000   2.652482  13.361702  11.865248   2.475177   0.063830   

              0.2       0.3          7  ...      0.21  0.22      0.23  \
cluster                                 ...                             
0        0.000000  0.000000   0.000000  ...  5.354839   0.0  0.000000   
1        0.008475  0.004237   2.728814  ...  0.000000   0.0  0.300847   
2        0.000000  0.000000   2.238095  ...  0.007326   0.0  0.087912   
3        0.000000  0.000000   0.000000  ...  0.000000   0.0  0.089041   
4        0.000000  0.000000   1.085366  ...  0.000000   0.0  0.445122   
5        0.000000  0.000000   0.010526  ...  0.647368   0.0  0.000000   
6        0.000000  0.000000   0.409722  ...  0.000000   0.0  0.062500   
7        2.444444  0.000000   0.074074  ...  0.000000   0.0  0.000000   
8        0.000000  0.000000   1.582090  ...  2.492537   0.0  0.074627   
9        0.000000  0.000000   0.418301  ...  0.098039   0.0  0.058824   
10       0.000000  0.000000   1.576923  ...  0.000000   0.0  0.010989   
11       0.000000  0.000000   7.144578  ...  0.024096   0.0  4.566265   
12       7.847826  0.000000   0.173913  ...  0.000000   0.0  0.000000   
13       0.000000  0.000000   0.000000  ...  0.000000   0.0  0.095238   
14       0.493976  0.000000   0.391566  ...  0.000000   0.0  0.132530   
15       0.000000  0.000000   1.337580  ...  0.267516   0.0  0.089172   
16       0.000000  0.000000   0.748691  ...  0.000000   0.0  0.010471   
17       0.000000  0.000000   0