In [108]:
import numpy as np
a1=np.array([[2,3,5,9,7],[3,2,4,2,4]])
b1=np.array([[20,30],[30,20],[40,50],[30,20]])
type(a)

numpy.ndarray

In [109]:
#Some Array Attributes 
a.shape
a.size
a.nbytes
b.ndim

1

In [110]:
x=np.array([[2,2],[3,3]])
y=np.array([[4,4],[5,5]])

In [182]:
#Functions
ls=a.flatten() # will convert 2d 3d into 1d
b1.reshape((2,4))
z=np.concatenate((x,y))
np.nonzero(a1)
# np.vsplit(b1,4)
# np.vsplit(b1,2)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int64))

In [228]:
a=np.arange(12)
b=np.random.normal(10,1,100)
c=np.random.uniform(0,100,10)
np.floor(c)


array([48., 34., 76., 48., 82., 90., 16., 93., 79., 51.])

In [156]:
d=np.array([[1,2,3,4],[5,6,7,8],[11,22,33,44],[55,66,77,88]])
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44],
       [55, 66, 77, 88]])

In [213]:
d[2:4,2:4]  # before commas : , : rows after commas columns
d[0:3,[0,3]] # fancy Slicing 

array([[ 1,  4],
       [ 5,  8],
       [11, 44]])

In [218]:
d[d>3] # Maasking 
d[d<10]
np.where(d<10 , d , np.nan)


array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

In [223]:
np.fill_diagonal(a1,10)
b1.fill(np.nan)
np.square(a1)
# np.add(a1,b1)
c.max()
a1.min()
a1.mean()
a1.argmin()

8